version: '3.5'

services:
  # db:
  #   container_name: db
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-item}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #     PGDATA: /data/postgres
  #   volumes:
  #      - postgres:/data/postgres
  #   ports:
  #     - "5432:5432"
  server:
    container_name: server
    image: item-node-server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - POSTGRES_HOSTNAME=postgres
    depends_on:
      db:
        condition: service_started
  web: 
    container_name: web
    image: item-web-react
    ports:
      - "3000:3000"
volumes: 
  postgres: