version: '3.5'

services:
  postgres:
    container_name: item_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-item}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes: 
  postgres: