version: '3.5'

services:
  db-full:
    container_name: db-full
    image: postgres:latest
    environment:
      POSTGRES_DB: item
      POSTGRES_USER: ${POSTGRES_USER:-item}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
  full: 
    container_name: item-module-full
    image: item-module-full
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - POSTGRES_HOSTNAME=db-full
      - POSTGRES_PASSWORD=password
      - POSTGRES_USERNAME=item
      - POSTGRES_DATABASE=item
      - NODE_ENV=production
    depends_on:
      - db-full
    restart: always
volumes: 
  postgres: