version: '3.5'

services:
  # db:
  #   container_name: db
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-item}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #     PGDATA: /data/postgres
  #   volumes:
  #      - postgres:/data/postgres
  #   ports:
  #     - "5432:5432"
  full: 
    container_name: item-module-full
    image: item-module-full
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - POSTGRES_HOSTNAME=postgres
    depends_on:
      db:
        condition: service_started
volumes: 
  db: